# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  expo-dev:
    desc: Run the Expo Dev Server
    cmds:
      - docker compose up dev -d
      - sleep 2
      - docker compose exec -ti dev npm install
      - docker compose exec -ti dev sh
    silent: true


  expo-start:
    desc: Run the Expo Dev Server
    cmds:
      - docker compose up dev -d
      - sleep 2
      - docker compose exec -ti dev npm install
      - docker compose exec -ti dev npm start
    silent: true


  expo-build:
    desc: Run the local build scripts for Android Expo
    cmds:
      - docker compose up builder -d
      - sleep 2
      - docker compose exec -ti builder npm ci
      - docker compose exec -ti builder npx expo prebuild --platform android
      - docker compose exec -ti builder sh -c 'cd android && ./gradlew assembleRelease'
      - cp android/app/build/outputs/apk/release/app-release.apk ./open-sleep-sounds.apk
    silent: true


  expo-stop:
    desc: Stop the Expo Server
    cmds:
      - docker compose down
    silent: true
